//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightAlliance.Orders.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreightAlliance.Orders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2engineer.
        /// </summary>
        public static string _2_engineer {
            get {
                return ResourceManager.GetString("2 engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Mate.
        /// </summary>
        public static string _2Mate {
            get {
                return ResourceManager.GetString("2Mate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3engineer .
        /// </summary>
        public static string _3_engineer {
            get {
                return ResourceManager.GetString("3 engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Mate.
        /// </summary>
        public static string _3Mate {
            get {
                return ResourceManager.GetString("3Mate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4engineer .
        /// </summary>
        public static string _4_engineer {
            get {
                return ResourceManager.GetString("4 engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Offer.
        /// </summary>
        public static string AddOfferText {
            get {
                return ResourceManager.GetString("AddOfferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add order position.
        /// </summary>
        public static string AddOrderPositionText {
            get {
                return ResourceManager.GetString("AddOrderPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add spare parts Order.
        /// </summary>
        public static string AddSparePartsOrderText {
            get {
                return ResourceManager.GetString("AddSparePartsOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add supply Order.
        /// </summary>
        public static string AddSupplyOrderText {
            get {
                return ResourceManager.GetString("AddSupplyOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All received.
        /// </summary>
        public static string AllReceivedColumnText {
            get {
                return ResourceManager.GetString("AllReceivedColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountText {
            get {
                return ResourceManager.GetString("AmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationController.
        /// </summary>
        public static string ApplicationController {
            get {
                return ResourceManager.GetString("ApplicationController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief engineer.
        /// </summary>
        public static string Chief_engineer {
            get {
                return ResourceManager.GetString("Chief engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief officer.
        /// </summary>
        public static string Chief_officer {
            get {
                return ResourceManager.GetString("Chief officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodeText {
            get {
                return ResourceManager.GetString("CodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Type.
        /// </summary>
        public static string CodeTypeText {
            get {
                return ResourceManager.GetString("CodeTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string CommentsColumnText {
            get {
                return ResourceManager.GetString("CommentsColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm receipt.
        /// </summary>
        public static string ConfirmReceiptText {
            get {
                return ResourceManager.GetString("ConfirmReceiptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook.
        /// </summary>
        public static string Cook {
            get {
                return ResourceManager.GetString("Cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new order.
        /// </summary>
        public static string CreateNewOrderText {
            get {
                return ResourceManager.GetString("CreateNewOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDateText {
            get {
                return ResourceManager.GetString("CreationDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curency.
        /// </summary>
        public static string CurencyText {
            get {
                return ResourceManager.GetString("CurencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager.
        /// </summary>
        public static string DataManager {
            get {
                return ResourceManager.GetString("DataManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received at office.
        /// </summary>
        public static string DateAtOfficeColumnText {
            get {
                return ResourceManager.GetString("DateAtOfficeColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete date.
        /// </summary>
        public static string DeleteDateColumnText {
            get {
                return ResourceManager.GetString("DeleteDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Offer.
        /// </summary>
        public static string DeleteOfferText {
            get {
                return ResourceManager.GetString("DeleteOfferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete order position.
        /// </summary>
        public static string DeleteOrderPositionText {
            get {
                return ResourceManager.GetString("DeleteOrderPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete order.
        /// </summary>
        public static string DeleteOrderText {
            get {
                return ResourceManager.GetString("DeleteOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete reason.
        /// </summary>
        public static string DeleteReasonColumnText {
            get {
                return ResourceManager.GetString("DeleteReasonColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter delete reason: .
        /// </summary>
        public static string DeleteReasonEditText {
            get {
                return ResourceManager.GetString("DeleteReasonEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        public static string DrawingText {
            get {
                return ResourceManager.GetString("DrawingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string FileText {
            get {
                return ResourceManager.GetString("FileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string InvoiceColumnText {
            get {
                return ResourceManager.GetString("InvoiceColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceManager.
        /// </summary>
        public static string InvoiceManager {
            get {
                return ResourceManager.GetString("InvoiceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string InvoiceText {
            get {
                return ResourceManager.GetString("InvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code.
        /// </summary>
        public static string ItemCodeText {
            get {
                return ResourceManager.GetString("ItemCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string MainText {
            get {
                return ResourceManager.GetString("MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured.
        /// </summary>
        public static string ManufacturedText {
            get {
                return ResourceManager.GetString("ManufacturedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured year.
        /// </summary>
        public static string ManufacturedYearText {
            get {
                return ResourceManager.GetString("ManufacturedYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master .
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Befor sending to the office. You must add positions.
        /// </summary>
        public static string NeedOrderPositionText {
            get {
                return ResourceManager.GetString("NeedOrderPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewText {
            get {
                return ResourceManager.GetString("NewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalize.
        /// </summary>
        public static string NextStatusText {
            get {
                return ResourceManager.GetString("NextStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Appropriate Status.
        /// </summary>
        public static string NotAppropriateStatusText {
            get {
                return ResourceManager.GetString("NotAppropriateStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberText {
            get {
                return ResourceManager.GetString("NumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print form.
        /// </summary>
        public static string OpenReportText {
            get {
                return ResourceManager.GetString("OpenReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order comment:.
        /// </summary>
        public static string OrderCommentText {
            get {
                return ResourceManager.GetString("OrderCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string OrderDateColumnText {
            get {
                return ResourceManager.GetString("OrderDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date:.
        /// </summary>
        public static string OrderDateText {
            get {
                return ResourceManager.GetString("OrderDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order №.
        /// </summary>
        public static string OrderNumberColumnText {
            get {
                return ResourceManager.GetString("OrderNumberColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order positions.
        /// </summary>
        public static string OrderPositionText {
            get {
                return ResourceManager.GetString("OrderPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status:.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order status.
        /// </summary>
        public static string OrderStatusColumnText {
            get {
                return ResourceManager.GetString("OrderStatusColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderText {
            get {
                return ResourceManager.GetString("OrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order total.
        /// </summary>
        public static string OrderTotalText {
            get {
                return ResourceManager.GetString("OrderTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order type.
        /// </summary>
        public static string OrderTypeColumnText {
            get {
                return ResourceManager.GetString("OrderTypeColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part number type.
        /// </summary>
        public static string PartNumberTypeColumnText {
            get {
                return ResourceManager.GetString("PartNumberTypeColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number Type.
        /// </summary>
        public static string PartNumberTypeText {
            get {
                return ResourceManager.GetString("PartNumberTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part serial number.
        /// </summary>
        public static string PartSerialNumberText {
            get {
                return ResourceManager.GetString("PartSerialNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person name:.
        /// </summary>
        public static string PersonNameText {
            get {
                return ResourceManager.GetString("PersonNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person post:.
        /// </summary>
        public static string PersonPostText {
            get {
                return ResourceManager.GetString("PersonPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate.
        /// </summary>
        public static string PlateText {
            get {
                return ResourceManager.GetString("PlateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in Drawning.
        /// </summary>
        public static string PosInDrawningText {
            get {
                return ResourceManager.GetString("PosInDrawningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PriceText {
            get {
                return ResourceManager.GetString("PriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityText {
            get {
                return ResourceManager.GetString("QuantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received At Office Date.
        /// </summary>
        public static string ReceivedAtOfficeDateText {
            get {
                return ResourceManager.GetString("ReceivedAtOfficeDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received At Vessel Date.
        /// </summary>
        public static string ReceivedAtVesselDateText {
            get {
                return ResourceManager.GetString("ReceivedAtVesselDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved.
        /// </summary>
        public static string ReceivedColumnText {
            get {
                return ResourceManager.GetString("ReceivedColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received date.
        /// </summary>
        public static string ReceivedDateText {
            get {
                return ResourceManager.GetString("ReceivedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string RemarksText {
            get {
                return ResourceManager.GetString("RemarksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request date.
        /// </summary>
        public static string RequestDateColumnText {
            get {
                return ResourceManager.GetString("RequestDateColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request date:.
        /// </summary>
        public static string RequestDateText {
            get {
                return ResourceManager.GetString("RequestDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string RequestsText {
            get {
                return ResourceManager.GetString("RequestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save order position.
        /// </summary>
        public static string SaveOrderPositionText {
            get {
                return ResourceManager.GetString("SaveOrderPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string SelectedText {
            get {
                return ResourceManager.GetString("SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select offer.
        /// </summary>
        public static string SelectInvoiceText {
            get {
                return ResourceManager.GetString("SelectInvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send for quotation.
        /// </summary>
        public static string SendForQuotationText {
            get {
                return ResourceManager.GetString("SendForQuotationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendText {
            get {
                return ResourceManager.GetString("SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To Office Date.
        /// </summary>
        public static string SentToOfficeDateText {
            get {
                return ResourceManager.GetString("SentToOfficeDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage place.
        /// </summary>
        public static string StoragePlaceColumnText {
            get {
                return ResourceManager.GetString("StoragePlaceColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Place is Not Specified.
        /// </summary>
        public static string StoragePlaceNotSpecifiedText {
            get {
                return ResourceManager.GetString("StoragePlaceNotSpecifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superintendant.
        /// </summary>
        public static string Superintendant {
            get {
                return ResourceManager.GetString("Superintendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string SupplierColumnText {
            get {
                return ResourceManager.GetString("SupplierColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierManager.
        /// </summary>
        public static string SupplierManager {
            get {
                return ResourceManager.GetString("SupplierManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply for.
        /// </summary>
        public static string SupplyForText {
            get {
                return ResourceManager.GetString("SupplyForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitText {
            get {
                return ResourceManager.GetString("UnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserText {
            get {
                return ResourceManager.GetString("UserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel.
        /// </summary>
        public static string VesselColumnText {
            get {
                return ResourceManager.GetString("VesselColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel.
        /// </summary>
        public static string VesselText {
            get {
                return ResourceManager.GetString("VesselText", resourceCulture);
            }
        }
    }
}
