//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightAlliance.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreightAlliance.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2engineer.
        /// </summary>
        public static string _2_engineer {
            get {
                return ResourceManager.GetString("2 engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2Mate.
        /// </summary>
        public static string _2Mate {
            get {
                return ResourceManager.GetString("2Mate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3engineer .
        /// </summary>
        public static string _3_engineer {
            get {
                return ResourceManager.GetString("3 engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3Mate.
        /// </summary>
        public static string _3Mate {
            get {
                return ResourceManager.GetString("3Mate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4engineer .
        /// </summary>
        public static string _4_engineer {
            get {
                return ResourceManager.GetString("4 engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLocalText {
            get {
                return ResourceManager.GetString("ChangeLocalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief engineer.
        /// </summary>
        public static string Chief_engineer {
            get {
                return ResourceManager.GetString("Chief engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief officer.
        /// </summary>
        public static string Chief_officer {
            get {
                return ResourceManager.GetString("Chief officer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cook.
        /// </summary>
        public static string Cook {
            get {
                return ResourceManager.GetString("Cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master .
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Incorrect.
        /// </summary>
        public static string PasswordIsIncorrectText {
            get {
                return ResourceManager.GetString("PasswordIsIncorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionText {
            get {
                return ResourceManager.GetString("PositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string SelectText {
            get {
                return ResourceManager.GetString("SelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superintendant.
        /// </summary>
        public static string Superintendant {
            get {
                return ResourceManager.GetString("Superintendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech Service.
        /// </summary>
        public static string TechServiceText {
            get {
                return ResourceManager.GetString("TechServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does Not Exist.
        /// </summary>
        public static string UserDoesNotExistText {
            get {
                return ResourceManager.GetString("UserDoesNotExistText", resourceCulture);
            }
        }
    }
}
