//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightAlliance.Invoices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreightAlliance.Invoices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add invoice.
        /// </summary>
        public static string AddInvoiceText {
            get {
                return ResourceManager.GetString("AddInvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountText {
            get {
                return ResourceManager.GetString("AmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyText {
            get {
                return ResourceManager.GetString("CurrencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Invice.
        /// </summary>
        public static string DeleteInvoiceText {
            get {
                return ResourceManager.GetString("DeleteInvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Amount.
        /// </summary>
        public static string DeliveryAmountText {
            get {
                return ResourceManager.GetString("DeliveryAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Invoice.
        /// </summary>
        public static string EditInvoiceText {
            get {
                return ResourceManager.GetString("EditInvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Paid.
        /// </summary>
        public static string FullyPaidText {
            get {
                return ResourceManager.GetString("FullyPaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string InvoiceDateText {
            get {
                return ResourceManager.GetString("InvoiceDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string InvoiceText {
            get {
                return ResourceManager.GetString("InvoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string MainText {
            get {
                return ResourceManager.GetString("MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string PaidAmountText {
            get {
                return ResourceManager.GetString("PaidAmountText", resourceCulture);
            }
        }
    }
}
